begin;
create index on push.nychpd_registration(id);
create index on push.nychpd_registration(bbl);
create index on push.nychpd_registration(building_id);
create index on push.nychpd_registration(house_number,street_name,zip);
create index on push.nychpd_registration(house_number,street_name,boro_id);
create index on push.nychpd_contact(id);
create index on push.nychpd_contact(contact_type);
create index on push.nychpd_contact(registration_id);
create index on push.nychpd_contact_rank(contact_type);
commit;
