
/* 

Raw CSV header:

  ISN_DOB_BIS_EXTRACT,ECB_VIOLATION_NUMBER,ECB_VIOLATION_STATUS,DOB_VIOLATION_NUMBER,
  BIN,BORO,BLOCK,LOT,HEARING_DATE,HEARING_TIME,SERVED_DATE,ISSUE_DATE,SEVERITY,VIOLATION_TYPE,
  RESPONDENT_NAME,RESPONDENT_HOUSE_NUMBER,RESPONDENT_STREET,RESPONDENT_CITY,RESPONDENT_ZIP,
  VIOLATION_DESCRIPTION,
  PENALITY_IMPOSED,AMOUNT_PAID,BALANCE_DUE,
  INFRACTION_CODE1,SECTION_LAW_DESCRIPTION1,
  INFRACTION_CODE2,SECTION_LAW_DESCRIPTION2,
  INFRACTION_CODE3,SECTION_LAW_DESCRIPTION3,   
  INFRACTION_CODE4,SECTION_LAW_DESCRIPTION4,
  INFRACTION_CODE5,SECTION_LAW_DESCRIPTION5,
  INFRACTION_CODE6,SECTION_LAW_DESCRIPTION6,
  INFRACTION_CODE7,SECTION_LAW_DESCRIPTION7,
  INFRACTION_CODE8,SECTION_LAW_DESCRIPTION8,
  INFRACTION_CODE9,SECTION_LAW_DESCRIPTION9,
  INFRACTION_CODE10,SECTION_LAW_DESCRIPTION10,
  AGGRAVATED_LEVEL,HEARING_STATUS,CERTIFICATION_STATUS

And a sample row:

  758705,34830294Z,RESOLVE,012910STFJH04,
  4080791,4,03388,0022,20100525,1030,20100401,20100129,Unknown,Unknown,
  THE HARMAN GROUP,1920,HARMAN STREET,FLUSHING,11385,
  FAILURE TO COMPLY EITH COMM ORDER TO FILE A CERT OF CORRECTION WITH THE DEPT OF BLDGS.NOTED:RESPONDENT FAILED TO COMPLY WITH THE COMMISSIONERS ORDER TO CORRECT THE VIOLATIING CONDITONS AND FILE A CERT OF CORR,
  4000.00,937.89,.00,263,
  AC 28-204.4                                                                 FAIL TO COMPLY W/COMMISSIONER ORDER TO FILE CERT OF CORRECTION W/DOB,,
  ,,,,,,,,,,,,,,,,,
  NO,DEFAULT,CERTIFICATE ACCEPTED
*/

begin;

drop table if exists flat.ecb_violation cascade;
create table flat.ecb_violation (
    ISN_DOB_BIS_EXTRACT integer,
    ECB_VIOLATION_NUMBER text,
    ECB_VIOLATION_STATUS text,
    DOB_VIOLATION_NUMBER text,
    BIN text, -- sometimes garbled, eg 'Z391875'
    BORO integer, 
    BLOCK text, -- sometimes garbled
    LOT text, -- sometimes empty
    HEARING_DATE date, -- YYYYMMDD
    HEARING_TIME smallint, -- HHMM
    SERVED_DATE text, -- should be YYYYMMDD but sometimes 0
    ISSUE_DATE text, -- should be YYYYMMDD but sometimes 0
    SEVERITY text,
    VIOLATION_TYPE text,
    RESPONDENT_NAME text,
    RESPONDENT_HOUSE_NUMBER text,
    RESPONDENT_STREET text,
    RESPONDENT_CITY text,
    RESPONDENT_ZIP text,
    VIOLATION_DESCRIPTION text,
    PENALITY_IMPOSED float,
    AMOUNT_PAID float,
    BALANCE_DUE float,
    INFRACTION_CODE1 text,SECTION_LAW_DESCRIPTION1 text,
    INFRACTION_CODE2 text,SECTION_LAW_DESCRIPTION2 text,
    INFRACTION_CODE3 text,SECTION_LAW_DESCRIPTION3 text,   
    INFRACTION_CODE4 text,SECTION_LAW_DESCRIPTION4 text,
    INFRACTION_CODE5 text,SECTION_LAW_DESCRIPTION5 text,
    INFRACTION_CODE6 text,SECTION_LAW_DESCRIPTION6 text,
    INFRACTION_CODE7 text,SECTION_LAW_DESCRIPTION7 text,
    INFRACTION_CODE8 text,SECTION_LAW_DESCRIPTION8 text,
    INFRACTION_CODE9 text,SECTION_LAW_DESCRIPTION9 text,
    INFRACTION_CODE10 text,SECTION_LAW_DESCRIPTION10 text,
    AGGRAVATED_LEVEL text, 
    HEARING_STATUS text,
    CERTIFICATION_STATUS text
);

commit;
